### ISSUE TITLE
"solo2 app oath" does not work correctly

### ISSUE THREAD

**Issue by skyrivad** [solokeys/solo2-cli#62]
# Software version

```sh
$ solo2 --version
solo2 0.1.1

$ solo2 app admin version
1:20200101.9

$ hostnamectl
Operating System: Pop!_OS 21.10                   
Kernel: Linux 5.16.11-76051611-generic
Architecture: x86-64
```

# Steps to reproduce

```sh
$ export SECRET=$(head -c 32 /dev/urandom|base32 -w0)

$ solo2 app oath register example ${SECRET}
example

$ solo2 app oath totp example
Error: p1/p2 parameters not supported on this transport

$ solo2 app oath list
thread 'main' panicked at 'explicit panic', /home/davideriva/.cargo/registry/src/github.com-1ecc6299db9ec823/solo2-0.1.1/src/transport/ctap.rs:90:18
stack backtrace:
   0:     0x55e23515803c - std::backtrace_rs::backtrace::libunwind::trace::h91c465e73bf6c785
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e23515803c - std::backtrace_rs::backtrace::trace_unsynchronized::hae9da36f5d58b5f3
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e23515803c - std::sys_common::backtrace::_print_fmt::h7f499fa126a7effb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55e23515803c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55e23517d1ec - core::fmt::write::h753c7571fa063ecb
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0x55e235150d93 - std::io::Write::write_fmt::h2815c0519c99ba09
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0x55e23515a8e2 - std::sys_common::backtrace::_print::h64941a6fc8b0ed9b
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55e23515a8e2 - std::sys_common::backtrace::print::hcf25e43e1a9b0766
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55e23515a8e2 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0x55e23515a4c5 - std::panicking::default_hook::hda898f8d3ad1a5ae
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0x55e23515af33 - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:606:17
  11:     0x55e23515ac22 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:500:13
  12:     0x55e2351584e4 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55e23515a989 - rust_begin_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
  14:     0x55e234eee561 - core::panicking::panic_fmt::h3a79a6a99affe1d5
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
  15:     0x55e234eee4ad - core::panicking::panic::h97167cd315d19cd4
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
  16:     0x55e234f3966b - <solo2::device::ctap::Device as solo2::transport::Transport>::call::h0cab9461d19d9864
  17:     0x55e234f1fde3 - <solo2::device::Solo2 as solo2::transport::Transport>::call::h1b4f3b7f26a22f66
  18:     0x55e234f0c984 - solo2::transport::Transport::instruct::h03a3301f5235c3a8
  19:     0x55e234f296df - solo2::apps::oath::App::list::h2ee6a571c175cb1a
  20:     0x55e234f01435 - solo2::try_main::hf2939f35317c5c42
  21:     0x55e234efe4c2 - solo2::main::hfd9fc59f365b416f
  22:     0x55e234f08353 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd039ae7e42400795
  23:     0x55e234f04389 - std::rt::lang_start::{{closure}}::h6c17aedab7191aa6
  24:     0x55e2351576f0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h443f738a8e9f947a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:259:13
  25:     0x55e2351576f0 - std::panicking::try::do_call::h1e21ba261ba489ec
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  26:     0x55e2351576f0 - std::panicking::try::h6afd48af8b6c96ac
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  27:     0x55e2351576f0 - std::panic::catch_unwind::h85dd95e0bab7fb60
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  28:     0x55e2351576f0 - std::rt::lang_start_internal::{{closure}}::h038455e697c8b03e
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:48
  29:     0x55e2351576f0 - std::panicking::try::do_call::h6b0ad65979f3077a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  30:     0x55e2351576f0 - std::panicking::try::h010108d314169ac6
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  31:     0x55e2351576f0 - std::panic::catch_unwind::hff397f912b1535c2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  32:     0x55e2351576f0 - std::rt::lang_start_internal::h52e73755f77c7dd9
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/rt.rs:128:20
  33:     0x55e234f03e62 - main
  34:     0x7fb96f92ffd0 - <unknown>
  35:     0x7fb96f93007d - __libc_start_main
  36:     0x55e234eeecd5 - _start
  37:                0x0 - <unknown>
```

**Comment by skyrivad** [comment]
Opened with the wrong account, moved to https://github.com/solokeys/solo2-cli/issues/63
