### ISSUE TITLE
Solo v2 reset

### ISSUE THREAD

**Issue by AndyKr0p** [solokeys/solo2-cli#77]
Hello,

I forgot what pin I created in Windows 10 for 1 solokey v2 and decided to reset it. I did it via oath reset on Win10, no errors returned - Win10 still says that "too many wrong PIN entered, contact IT administrator". I did reset on Mac M1 and it did not help as well. Next was an attempt to format solo on Mac, but it returns error:

./solo2-v0.2.0-x86_64-apple-darwin app provision reformat-filesystem
thread 'main' panicked at 'explicit panic', src/transport/ctap.rs:90:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

How to fully reset the key?

**Comment by theerror** [comment]
Actually, there is much more commands, what actually give this same error:

```
solo2 app ndef capabilities
thread 'main' panicked at 'explicit panic', /Users/jpleva/.cargo/registry/src/github.com-1ecc6299db9ec823/solo2-0.2.1/src/transport/ctap.rs:90:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
and some others what I found:
```
solo2 app ndef data
solo2 app oath list
```

I do have MacOS 12.6, with M1. 

solo2 app admin version
2:20220822.0

solo2 -V
solo2 0.2.1

**Comment by robinkunde** [comment]
I'm in the same boat. I've tried both solo1-cli and solo2-cli. Any ideas? @nickray

**Comment by theerror** [comment]
> I'm in the same boat. I've tried both solo1-cli and solo2-cli. Any ideas? @nickray

@robinkunde I've found out, that this issue is resolved by latest MacOS update Ventura

**Comment by holykol** [comment]
In case anyone is still wondering how to reset solo v2 you can visit `chrome://settings/securityKeys` in your Chromium-based browser.

<img width="679" height="446" alt="securityKeys settings page" src="https://github.com/user-attachments/assets/b396ef68-5dc2-4f4e-92fb-2889982e8501" />
